---
- name : app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: install Maven and Mysql 
  ansible.builtin.import_role: 
    name: common
    tasks_from: java.yaml

- name: install mysql python dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL
  

- name : load shipping schema
  community.mysql.mysql_db:

    state: import
    name: all
    target: /app/schema/shipping.sql
    login_host: "{{ mysql_host }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    target: "{{item}}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name : system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml

  

  