---
- name: create user and app directory
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: install python packages and dependencies
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml


- name: service file setup and start payment service
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml
  notify: 